spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/ensam_bibliotheque_prod?useSSL=false&serverTimezone=UTC
    username: root
    password: root
