/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppLoansIndexRouteImport } from './routes/_app.loans.index'
import { Route as AppBooksIndexRouteImport } from './routes/_app.books.index'
import { Route as AppLoansMyRouteImport } from './routes/_app.loans.my'
import { Route as AppBooksNewRouteImport } from './routes/_app.books.new'
import { Route as AppBooksBookIdRouteImport } from './routes/_app.books.$bookId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansIndexRoute = AppLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksIndexRoute = AppBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansMyRoute = AppLoansMyRouteImport.update({
  id: '/loans/my',
  path: '/loans/my',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksNewRoute = AppBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBooksBookIdRoute = AppBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/users': typeof AppUsersRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/books/new': typeof AppBooksNewRoute
  '/loans/my': typeof AppLoansMyRoute
  '/books/': typeof AppBooksIndexRoute
  '/loans/': typeof AppLoansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/profile': typeof AppProfileRoute
  '/users': typeof AppUsersRoute
  '/books/$bookId': typeof AppBooksBookIdRoute
  '/books/new': typeof AppBooksNewRoute
  '/loans/my': typeof AppLoansMyRoute
  '/books': typeof AppBooksIndexRoute
  '/loans': typeof AppLoansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/books/$bookId': typeof AppBooksBookIdRoute
  '/_app/books/new': typeof AppBooksNewRoute
  '/_app/loans/my': typeof AppLoansMyRoute
  '/_app/books/': typeof AppBooksIndexRoute
  '/_app/loans/': typeof AppLoansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/categories'
    | '/dashboard'
    | '/profile'
    | '/users'
    | '/books/$bookId'
    | '/books/new'
    | '/loans/my'
    | '/books/'
    | '/loans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/categories'
    | '/dashboard'
    | '/profile'
    | '/users'
    | '/books/$bookId'
    | '/books/new'
    | '/loans/my'
    | '/books'
    | '/loans'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/profile'
    | '/_app/users'
    | '/_app/books/$bookId'
    | '/_app/books/new'
    | '/_app/loans/my'
    | '/_app/books/'
    | '/_app/loans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/': {
      id: '/_app/loans/'
      path: '/loans'
      fullPath: '/loans/'
      preLoaderRoute: typeof AppLoansIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/': {
      id: '/_app/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AppBooksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/loans/my': {
      id: '/_app/loans/my'
      path: '/loans/my'
      fullPath: '/loans/my'
      preLoaderRoute: typeof AppLoansMyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/new': {
      id: '/_app/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof AppBooksNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/books/$bookId': {
      id: '/_app/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof AppBooksBookIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppUsersRoute: typeof AppUsersRoute
  AppBooksBookIdRoute: typeof AppBooksBookIdRoute
  AppBooksNewRoute: typeof AppBooksNewRoute
  AppLoansMyRoute: typeof AppLoansMyRoute
  AppBooksIndexRoute: typeof AppBooksIndexRoute
  AppLoansIndexRoute: typeof AppLoansIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppUsersRoute: AppUsersRoute,
  AppBooksBookIdRoute: AppBooksBookIdRoute,
  AppBooksNewRoute: AppBooksNewRoute,
  AppLoansMyRoute: AppLoansMyRoute,
  AppBooksIndexRoute: AppBooksIndexRoute,
  AppLoansIndexRoute: AppLoansIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
