name: CI-CD

on:
  push:
    branches:
      - main
      - M-Yassir-branch-2

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # Backend

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Test Backend
        working-directory: backend
        run: mvn clean test

      - name: Package Backend
        working-directory: backend
        run: mvn clean package -DskipTests

      # Frontend

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

  deploy:

    needs: build

    runs-on: self-hosted

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop old containers
        run: docker compose down

      - name: Rebuild and Deploy
        run: docker compose up -d --build

      - name: Verify
        run: docker ps